version: '3.8'

services:
  db:
    image: postgres:16
    container_name: calculoinvestimento_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devteste2025
      POSTGRES_DB: calculoinvestimento
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: CalculoInvestimento.WebApi/Dockerfile
    container_name: calculoinvestimento_webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=calculoinvestimento;Username=dev;Password=devteste2025
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: